apiVersion: v1
kind: Pod
metadata:
  name: python-microservice-pod
  namespace: tech.prod
spec:
  containers:
  - name: python-microservice-container
    image: prueba:v1          #your-dockerhub-username/your-image-name:latest
    ports:
    - containerPort: 5000
    resources:
      limits:
        memory: "3Gi"
    env:
    - name: ENVIRONMENT
      value: "production"
  nodeSelector:
    network: "internal prod"
